server:
  port: 7001

eureka:
  instance:
    #    hostname: localhost  #eureka服务端的实例名字
    hostname: eureka7001.com  #eureka服务端的实例名字(#集群版)

  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#      defaultZone: http://eureka7002.com:7002/eureka/  #集群版

